### ISSUE TITLE
Talktorial T013 .ipynb is missing in the master repo for Query Klifs

### ISSUE THREAD

**Issue by Carlbullish** [volkamerlab/teachopencadd#110]
I had to check the t011 branch to get the tutorial and all the codes in there seem fine. The team can have a look into it. Thanks for the awesome job. Getting to know about TeachOpenCADD is one of the best things that has happened to me this year.

**Comment by dominiquesydow** [comment]
Hi @Carlbullish, that is wonderful - very happy to hear this!

The current `master` branch officially only contains T001-T010, while the notebooks >T011 are still work in progress, which runs on `t011-base` as you already found out. If you find bugs or have suggestions, we are happy to hear about them, so that it can be fixed before merging the new material into `master`.

FYI: This is the PR with the new notebooks: https://github.com/volkamerlab/teachopencadd/pull/74

Have fun with the material!

**Comment by Carlbullish** [comment]
Alright.. Thanks. I wished they were out already :)
