### ISSUE TITLE
Jupyter Lab 3

### ISSUE THREAD

**Issue by jaimergp** [volkamerlab/teachopencadd#80]
This is going to be released soon, which enables dynamic extensions. This will allow us to provide a package that works right away without having to worry about `jupyter labextension install bla bla bla`. Leaving this here so I don't forget to update the environment and recipe :)

**Comment by dominiquesydow** [comment]
Hi @volkamerlab/core,

When I am installing our [test environment `test_env.yaml`](https://github.com/volkamerlab/opencadd/blob/master/devtools/conda-envs/test_env.yaml) from scratch, I am running into errors when displaying widgets with `nglview` using JupyterLab 3.

![image](https://user-images.githubusercontent.com/7207093/104199063-43a0c700-5427-11eb-9a96-e9161eb3866d.png)

I think this will stay that way for a bit, see https://github.com/nglviewer/nglview/issues/932, which is fine. Please do check if you have the same problem or if I just missed something here.

If this problem is reproducible, we should pin our environment to JupyterLab 2 for now. @jaimergp, let me know what you think, please :)

Test environment still works nicely (plus manual install of nodejs and Jupyterlab extensions as defined in yaml file):
![image](https://user-images.githubusercontent.com/7207093/104199333-97131500-5427-11eb-909d-bf21925f3a46.png)

**Comment by jaimergp** [comment]
I haven't tested it yet, but pinning sounds like a good idea if you already found some rough edges. Back-compatibility is in principle kept, but 🤷 

Let's pin for now but leave this open so we revisit that at some point in the (not so distant) future.

**Comment by dominiquesydow** [comment]
Ok, great, thanks! :)

Quick question regarding the where: I would pin it now in our refactoring base [`t011-base`](https://github.com/volkamerlab/teachopencadd/tree/t011-base) and everyone will need to update this before merging into `t011-base`, is that correct?

**Comment by jaimergp** [comment]
Let's do it in a PR targeting `master`, since the problem is affecting all notebooks already. We will rebase as needed.

**Comment by dominiquesydow** [comment]
True! Sounds better, will do that now.

**Comment by jaimergp** [comment]
Thank you!! 🥳
